import React, { useState } from "react";
import axios from "axios";
import "./App.css";

function App() {
  const [file, setFile] = useState(null);
  const [isUploading, setUploading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");

  const onFileChange = (e) => {
    setFile(e.target.files?.[0] || null);
    setResult(null);
    setError("");
  };

  async function mockAnalyze() {
    await new Promise((r) => setTimeout(r, 800));
    return {
      summary: "No anomalies detected (mock).",
      hints: [
        "Lighting consistent.",
        "No texture repetition.",
        "No tampering found."
      ],
    };
  }

  const handleUpload = async () => {
    try {
      if (!file) return;
      setUploading(true);
      setError("");

      // Mock for now (we'll hook this to your API later)
      const analysis = await mockAnalyze();
      setResult(analysis);
    } catch (e) {
      setError("Error during upload or analysis.");
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="app-container">
      {/* Sidebar */}
      <div className="sidebar">
                <div className="sidebar-header">
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <div className="logo-icon">�️</div>
            <h2>The FRAUDfather</h2>
          </div>
          <p>Detect AI-generated images at scale</p>
        </div>
        <nav className="sidebar-nav">
          <a href="#" className="nav-item active">🔍 AI Detection</a>
          <a href="#" className="nav-item">📊 Analytics</a>
          <a href="#" className="nav-item">🕒 History</a>
          <a href="#" className="nav-item">📁 Batch Processing</a>
          <a href="#" className="nav-item">⚙️ Settings</a>
          <a href="#" className="nav-item">❓ Help & Support</a>
        </nav>
        
        {/* Stats Card */}
        <div className="stats-card">
          <div className="stats-header">
            <span className="stats-icon">📈</span>
            <span className="stats-title">Detection Stats</span>
          </div>
          <div className="stats-content">
            <div className="stat-item">
              <span>Images analyzed:</span>
              <span className="stat-value purple">1,247</span>
            </div>
            <div className="stat-item">
              <span>AI-generated:</span>
              <span className="stat-value red">23%</span>
            </div>
            <div className="stat-item">
              <span>Accuracy:</span>
              <span className="stat-value green">98.7%</span>
            </div>
          </div>
        </div>
      </div>
      
      {/* Main Content */}
      <div className="main-content">
        {/* Header */}
        <header className="header">
          <div className="header-left">
            <div style={{ display: 'flex', alignItems: 'center' }}>
              <div className="logo-icon">🕵️</div>
              <h1>The FRAUDfather</h1>
            </div>
            <div className="ai-badge">
              <span className="pulse-dot"></span>
              AI-Powered Detection Engine
            </div>
          </div>
          <div className="header-right">
            <div className="accuracy-badge">✅ 98.7% Accuracy</div>
            <button className="settings-btn">⚙️ Settings</button>
          </div>
        </header>
        
        {/* Content Area */}
        <main className="content-area">
          {/* Hero Section */}
          <div className="hero-section">
            <h2>Detect AI-Generated Images at Scale</h2>
            <p>
              Leverage cutting-edge AI technology to detect artificially generated images 
              with industry-leading accuracy. Protect your business from deepfakes and synthetic media fraud.
            </p>
            <div className="feature-badges">
              <span className="feature-badge">🎯 98.7% Accuracy</span>
              <span className="feature-badge">⚡ Instant Analysis</span>
              <span className="feature-badge">🏢 Enterprise Ready</span>
            </div>
          </div>

          {/* Upload Card */}
          <div className="upload-card">
            <div className="card-header">
              <h3>🖼️ AI Image Detection</h3>
              <p>Upload an image to detect if it was generated by AI</p>
            </div>
            
            <div className="upload-section">
              <div className="file-input-wrapper">
                <input 
                  type="file" 
                  accept="image/*" 
                  onChange={onFileChange}
                  id="file-input"
                  className="file-input"
                />
                <label htmlFor="file-input" className="file-input-label">
                  📁 Choose File
                </label>
              </div>
              
              <button
                onClick={handleUpload}
                disabled={!file || isUploading}
                className="upload-btn"
              >
                {isUploading ? (
                  <>
                    <span className="spinner"></span>
                    Analyzing...
                  </>
                ) : (
                  <>
                    🚀 Upload & Analyze
                  </>
                )}
              </button>
            </div>

            {file && (
              <div className="file-preview">
                <div className="file-info">
                  <span className="file-name">📎 {file.name}</span>
                  <span className="file-size">({(file.size / 1024 / 1024).toFixed(2)} MB)</span>
                </div>
              </div>
            )}

            {error && (
              <div className="error-message">
                ❌ {error}
              </div>
            )}

            {result && (
              <div className="results-section">
                <h4>🤖 AI Analysis Results</h4>
                <div className="result-summary">
                  <span className="result-icon">✅</span>
                  <span>{result.summary}</span>
                </div>
                <div className="result-details">
                  <h5>📋 Analysis Details:</h5>
                  <ul>
                    {result.hints.map((h, i) => (
                      <li key={i}>
                        <span className="hint-icon">•</span>
                        {h}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>

          {/* How it Works Section */}
          <div className="how-it-works">
            <h3>🔬 How The FRAUDfather Works</h3>
            <div className="steps-grid">
              <div className="step-card">
                <div className="step-icon">📤</div>
                <h4>Upload</h4>
                <p>Upload your image file or drag and drop it into the analysis area</p>
              </div>
              <div className="step-card">
                <div className="step-icon">🔍</div>
                <h4>Analyze</h4>
                <p>Our AI scans for artifacts, patterns, and metadata inconsistencies</p>
              </div>
              <div className="step-card">
                <div className="step-icon">📊</div>
                <h4>Results</h4>
                <p>Get detailed results with confidence scores and analysis breakdown</p>
              </div>
            </div>
          </div>

          {/* Use Cases Section with Popups */}
          <div className="use-cases-section">
            <div className="popup-card left">
              <div className="popup-header">
                <span className="popup-tag">Insurance Claims</span>
              </div>
              <div className="popup-image insurance-image"></div>
              <div className="popup-content">
                <h4>Creating fake insurance claims with faked images of incidents at home.</h4>
                <p>Detect fraudulent property damage claims using AI-generated images of mold, fire, or water damage.</p>
              </div>
            </div>
            
            <div className="popup-card right">
              <div className="popup-header">
                <span className="popup-tag">Fake Photo Evidence</span>
              </div>
              <div className="popup-image accident-image"></div>
              <div className="popup-content">
                <h4>Generating fraudulent accident reports with AI-generated images.</h4>
                <p>Identify synthetic accident scene photos used to support false insurance or legal claims.</p>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}

export default App;
